project_id = "khnsqupkdnouimonughn"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-guest-checkout]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.get-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.reactivate-subscription]
verify_jwt = false

[functions.admin-get-users]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false